eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8070
spring:
  application:
    name: company
  
  datasource:
    networks:
      - postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/micro
    username: abhi
    password: abhi
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    employees-url: http://localhost:8222/api/v1/employee


management:
  tracing:
    sampling:
      probability: 1.0

